### ISSUE TITLE
Changes to writeType appear to be unreleased

### ISSUE THREAD

**Issue by ceddlyburge** [stil4m/elm-syntax#117] opened 2021-03-25 17:28 UTC
The definition of the writeType function that I have on my computer is different to the one in this repo (below)

https://github.com/stil4m/elm-syntax/blob/0fa8741e8b731c2472bec7e6c392ee09239b5b79/src/Elm/Writer.elm#L281

The version I have is missing the `indent 4` line, which was introduced 10 months ago to fix #30 

I am using version 7.2.1

I have just deleted elm-stuff and the global elm cache and re run, and I still don't have this version of the code.

I notice that the version in elm.json is still 7.1.3, so maybe this is causing the confusion?

https://github.com/stil4m/elm-syntax/blob/0fa8741e8b731c2472bec7e6c392ee09239b5b79/elm.json#L6

**Comment by jfmengels** [comment] 2021-03-25 19:17
Hi @ceddlyburge

The version in `master` has breaking changes, and we're not ready to release (not even close, since we'd like to batch a lot of breaking changes if possible). What you want to look for is the `v7` branch, as that is what is still getting released.

I tried backporting and there seem to be some conflicts. @MartinSStewart could you take a look at that? I'm not familiar with it and I don't know if the tests can be relied on (enough)

**Comment by ceddlyburge** [comment] 2021-03-25 20:18
Hi Jeroen that makes sense, and that change isn't on the v7 branch.

Is there any chance of making that change and doing a release? It's a trivial change, but I would be happy to create a PR if you would like.

Also, thanks for all your general Elm work :)

**Comment by MartinSStewart** [comment] 2021-03-25 20:20
I haven't quite understood what the issue is yet so if you want to go ahead and make a PR for one of us to review that's fine by me!

**Comment by ceddlyburge** [comment] 2021-03-25 20:36
No worries #118 should be with you now ....

**Comment by jfmengels** [comment] 2021-03-25 21:03
Released in version `7.2.2`!

**Closed by jfmengels** 2021-03-25 21:03 UTC

**Comment by ceddlyburge** [comment] 2021-03-25 21:07
Boom!

Thanks both, thats amazingly speedy and helpful :)
